### ISSUE TITLE
get_system_stats(action:"logs") over-redacts file paths and module names as «redacted», blocking custom-node import diagnosis

### ISSUE THREAD

**Issue by artokun** [artokun/comfyui-mcp#1223]
### What happened / root cause

`get_system_stats (action:"logs")` replaced ordinary filesystem paths and Python module names with `«redacted»`, making a routine custom-node import failure impossible to diagnose through the tool. The same information was returned UNREDACTED by the same tool earlier in the same session, so the behavior is inconsistent within one session.

Diagnosing an `IMPORT FAILED` requires exactly the two things being redacted: which pack failed (a path) and which module/symbol failed (a module name). Redacting both reduces the log tool to "something, somewhere, failed."

Early in the session (working):

```
2026-08-08T23:14:40 - [INFO]   10.8 seconds: /basedir/custom_nodes/comfyui-easy-use
2026-08-09T00:33:35 - [VRGDG] Created 12 placeholder text file(s) in /basedir/output/VRGDG_TEMP/TextFiles
  - .VRGDG_LTXLoopingSampler: ModuleNotFoundError: No module named 'ComfyUI-LTXVideo'
```

Later in the SAME session (broken):

```
[INFO]    0.0 seconds (IMPORT FAILED): «redacted»
  - «redacted»: ImportError: cannot import name 'pad' from '«redacted»' («redacted»)
[INFO]    0.0 seconds: «redacted»      (x26 — every custom node path)
```

Nothing about the environment changed between those two reads except ComfyUI restarts.

### Why this matters

These are not secrets. `/basedir/custom_nodes/<pack>` and `kornia.geometry.transform.pyramid` are public library paths. Redacting them:

1. Hid WHICH pack failed to import (the `IMPORT FAILED` line is path-only, so redaction removes 100% of its content).
2. Hid the module the missing symbol came from — the single most important field in an ImportError.
3. Broke keyword filtering. `keyword:"ltxvideo"` and `keyword:"LTXLoopingSampler"` both returned "No log lines found" even though matching lines existed, because the substrings had been replaced before the filter ran. That is actively misleading — it reports absence where there is a match.

### Steps to reproduce

1. Install a custom node whose import fails (any pack with a broken dependency).
2. Restart ComfyUI.
3. `get_system_stats (action:"logs", keyword:"IMPORT FAILED")` → the path is `«redacted»`.
4. `get_system_stats (action:"logs", keyword:"<the pack name>")` → "No log lines found", despite the line existing.

### Workaround used

Bypassed the MCP tool entirely and hit ComfyUI's own endpoint from the shell, which returned everything in the clear:

```bash
curl -s "http://<host>:8188/internal/logs/raw"
```

That immediately gave the real answer the MCP tool had hidden:

```
- .VRGDG_LTXLoopingSampler: ImportError: cannot import name 'pad' from
  'kornia.geometry.transform.pyramid' (/comfy/mnt/venv/lib/python3.12/site-packages/kornia/geometry/transform/pyramid.py)
Cannot import /basedir/custom_nodes/ComfyUI-LTXVideo module for custom nodes
```

An agent without shell access to the ComfyUI host would have been stuck. That is the real cost here.

### Fix

applied locally: no
upstream-only: yes (the redaction runs in the orchestrator/tool process; a local patch would not take effect without a full orchestrator restart)

Precise changes needed:

1. **Do not redact filesystem paths or dotted module names by default.** The scrubber should target credential shapes (`sk-…`, `ghp_…`, `Bearer …`, `?token=`, `Authorization:`, `.env` contents), not any path-like string. Whatever rule matched `/basedir/custom_nodes/comfyui-easy-use` and `kornia.geometry.transform.pyramid` is far too broad.

2. **Never redact before applying `keyword`.** Filter the RAW text, then scrub the surviving lines. Today a redacted substring silently makes a matching line unfindable, and the tool reports "No log lines found" — an absence it did not establish. This is the more dangerous half of the bug: wrong output rather than missing output.

3. **If a line genuinely must be scrubbed, say what class of thing was removed** (`«path»`, `«token»`) instead of a bare `«redacted»`, so the reader can tell a hidden secret from a hidden library path.

4. Investigate why it differed within one session — same tool, same host, unredacted at 23:14 and redacted at 10:12. Suggests state- or size-dependent scrubbing rather than a deterministic rule.

### Environment

OS: Linux (ComfyUI host) / Windows 11 Pro 26200 (orchestrator host)
ComfyUI: 0.30.0
ComfyUI FRONTEND: 1.47.12
Python 3.12.3 / PyTorch 2.13.0+cu129 / CUDA 12.9
GPU: NVIDIA RTX PRO 6000 Blackwell Workstation Edition, 95.0 GB VRAM
comfyui-mcp: 0.50.45
comfyui-mcp-panel: 0.11.44
Backend: Claude
Note: ComfyUI is REMOTE relative to the orchestrator, which is why the missing detail mattered.

Related (same root cause): #1206

**Comment by artokun** [comment]
**This is my regression, from #828.** The `«redacted»` marker traces to `src/comfyui/json-guard.ts` — the only file in `src/` that emits it — which is the URL-redaction I added in v0.50.49 for non-JSON response diagnosis.

The relevant history, since it explains the shape of the bug: that redactor started as a **blocklist** of sensitive param names, which leaked 9 of 16 probe URLs. I inverted it to a **fail-closed allowlist**, which then ate legitimate long values, so I added a `LONG_TEXT_PARAMS` exemption for `filename`, `subfolder`, `dir`, `template`. Fail-closed was the right call for URLs carrying tokens. Applying that same posture to **log text** is not — a log line is not a URL, and the two things being redacted here (which pack failed, which module failed) are precisely what an `IMPORT FAILED` diagnosis requires.

Your observation that the same tool returned the information **unredacted earlier in the same session** is the useful detail: that says the redaction is path-dependent, not blanket, which should make the trigger findable rather than a matter of taste.

I am not fixing it in this turn — I am out of context, and #1217 is already being rewritten. Filing this note now so it is not re-diagnosed from scratch: start at `json-guard.ts`, find why log text reaches a URL redactor at all, and treat "logs are not URLs" as the fix rather than widening the allowlist. Widening it is how the URL side got its first bug.

**Comment by artokun** [comment]
Fixed in **0.50.63**.

Both halves of what you reported were real, and both were regressions from #1206.

**The paths and module names.** The credential scrub had a shape rule that redacted any 24+ character run of `[A-Za-z0-9-._~+/=%]` — written on the reasoning that ordinary prose breaks well before 24 characters. True of prose, false of a log, where paths are most of the content. A long run is now split on `/` and `.` and each part judged separately: kept when it reads as a name, redacted when it reads as a blob. Your `IMPORT FAILED` line and the `cannot import name 'pad' from 'kornia.geometry.transform.pyramid'` line are both fixtures in the suite now, asserted byte-for-byte.

Measured against a real ComfyUI log on my machine: the old rule redacted inside **75 of 150 lines**; the new one alters none of them.

**The keyword filter — this was the worse half.** You are right that it is actively misleading, and the cause is that the filter ran *after* the redaction, so it was matching against text that had already been rewritten. Selection now happens inside `getLogs` on the raw log, ahead of the scrub, and raw lines never leave that function — so no future call site can reintroduce the ordering. Verified live: `keyword` searches now return all matching lines, where they previously returned none.

Worth saying plainly: a diagnostic tool that answers "No log lines found" for a line that is right there is worse than one that returns the line redacted, because it tells you to stop looking. That is the part I got wrong, and the ordering is now structural rather than a rule someone has to remember.

**What is still redacted:** a configured credential (by value, in every encoding), anything introduced by name (`token=`, `api_key:`), anything behind `Bearer`/`Basic` — that last one was a gap the old blunt rule had been covering by accident, found during review of this fix — and unstructured blobs. The remaining residual is stated exactly in the code: a secret this process does not hold, carrying no name and no scheme, spelled entirely in path-like parts, reads as a path. Closing that would mean redacting `/models/upscale_models/4x-UltraSharp.pth` again, which is the bug you filed.

Thanks for the `curl /internal/logs/raw` comparison — having the working and broken output from the same session is what made the cause unambiguous.
